### ISSUE TITLE
프론트엔드 레이아웃 구성

### ISSUE THREAD

**Issue by sss5793** [woowa-techcamp-2020/market-2#4]
1. base css 작성(색상, 정렬, 폰트 등), 이미지 추가
2. header, footer, layout 모듈화
3. 페이지 생성(메인, 로그인, 회원가입, 회원가입 완료)
4. validation 모듈화
5. 페이지 이동 기능 예시 추가
6. input, button 예시 추가

**Comment by Loloara** [comment]
#2 Merge 성공
