### ISSUE TITLE
node 서버 쪽 코드 require -> import 로 통일

### ISSUE THREAD

**Issue by Loloara** [woowa-techcamp-2020/market-2#44]
- [ ] es6 문법인 import from 을 사용하자!!

**Comment by sss5793** [comment]
적용 방법을 찾으셨나요?!

**Comment by sss5793** [comment]
babel 적용!

**Comment by Loloara** [comment]
[node.js에서 es6 코드 사용해보기(babel)](https://hoony-gunputer.tistory.com/entry/nodejs%EC%97%90%EC%84%9C-es6-%EC%BD%94%EB%93%9C-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0babel) 이 링크 위키 벡엔드탭에 추가했습니다
